name: Workflow principal
run-name: workflow principal sendo executado
on:
  push:
jobs:
  executa-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o clone do repositório e muda para branch correta (checkout)
        uses: actions/checkout@v5

      - name: Instalar o node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar as dependências
        run: npm install