name: workflow-principal
run-name: wokflow principal sendo executado
on:
  push:
jobs:
  executa-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o clone do repositório e muda para a branch correta (checkout)
        uses: actions/checkout@v5
      
      - name: Instalar o node na versão 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Instalar as dependências de execução
        run: npm install

      - name: Executar testes
        run: npm test
